/* accepts integer prod and determines if == product of consecutive fib numbers */
function productFib(prod){
  /* fib array stores the fib sequence generated by while loop */
  let fib = [0, 1]

  while (true){
    /* get last two integers from array */
    let last = fib[fib.length - 1]
    let prev = fib[fib.length - 2]

    /* check if prod found or passed */
    if (last * prev === prod) return [prev, last, true]
    if (last * prev > prod) return [prev, last, false]
      
    /* push next fib number to array */
    fib.push(last + prev)
  }
}